### ISSUE TITLE
Pull Request Challenge ideas

### ISSUE THREAD

**Issue by jscook** [rjbs/Pod-Elemental-Transformer-List#3]
Hello,

I have been assigned to this distribution for the CPAN Pull Request Challenge for February 2015 (see: http://neilb.org/2014/11/29/pr-challenge-2015.html).

I was wondering if you had any ideas for features or fixes that you'd like (see: http://neilb.org/2014/12/31/pr-ideas.html as well).

If not, I will go ahead and look through things myself and do my best to provide additional value to your distribution.

Thanks.

**Comment by rjbs** [comment]
Sorry for my delayed response, I was out of town and (*shudder*) almost entirely without Internet.

I've had a look at the code, and I am *amazed* to see that I have no immediate requests for improvement.  On the other hands, its tests seems pretty underwhelming.  If I got to have a wish granted, it might for *someone* to look at Devel::Cover reports for it and then improve them.

If you haven't used Devel::Cover before, and are interested, I'll walk you through it.

Thanks for your interest, and good luck with the challenge!

**Comment by jscook** [comment]
Thanks for the feedback and no worries about delayed responses.

I will take a look at the coverage and report back. I'm looking forward to getting a chance to dabble with a Dist::Zilla based distribution.

**Comment by jscook** [comment]
The coverage is not too bad actually. I'll see if I can find a way to introduce bad data and increase the conditional and branch coverage.

Reading database from /Users/jsc/Documents/github/Pod-Elemental-Transformer-List/cover_db

----------------------------------- ------ ------ ------ ------ ------ ------
File                                  stmt   bran   cond    sub   time  total
----------------------------------- ------ ------ ------ ------ ------ ------
...od/Elemental/Transformer/List.pm  100.0   79.1   66.6  100.0    3.4   92.3

**Comment by jscook** [comment]
I opened up some issues on my fork:

https://github.com/jscook/Pod-Elemental-Transformer-List/issues

Feel free to pick and choose which ones you like.

**Comment by jscook** [comment]
I put in a pull request so I'm going to close this open issue. Feel free to use it if you wish. Thanks for your help during this part of the challenge.
